### ISSUE TITLE
SEO missing

### ISSUE THREAD

**Issue by elisadcg** [Fenykepy/phiroom#1]
Some tags html are missing for a better SEO :
on the `<header></header>`

    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="nomprenom" />

Not for SEO but for fun :

    <link rel="shortcut icon" href="site/favicon.ico" type="image/x-icon"/>

Some SEO information for user are missing :
Explain that title receive max 70 characters (40 are better).
Explain that description receive max 170 characters.

`Sitemap.html` is missing on the CMS

Good luck !
regards

**Comment by Fenykepy** [comment]
Fixed in 277c58983de9f47bc351ed1b2b6369c4ac3edcc5
